version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install requests

  build:
    commands:
      - python call_api.py

artifacts:
  files:
    - output.txt